version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=XXXXXXXXX
      - ZONE=example.com
      - SUBDOMAIN=homenet
      - PROXIED=true