version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
  
    volumes:
      - '/docker_bind/nginxproxymanager/data:/data'
      - '/docker_bind/nginxproxymanager/letsencrypt:/etc/letsencrypt'

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s