version: '3.3'
services:
    autoheal:
        container_name: autoheal
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
            - AUTOHEAL_CONTAINER_LABEL=${AUTOHEAL_CONTAINER_LABEL:-autoheal}
            - AUTOHEAL_INTERVAL=${AUTOHEAL_INTERVAL:-5}   # check every 5 seconds
            - AUTOHEAL_START_PERIOD=${AUTOHEAL_START_PERIOD:-0}   # wait 0 seconds before first health check
            - AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AUTOHEAL_DEFAULT_STOP_TIMEOUT:-10}   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
            - DOCKER_SOCK=/var/run/docker.sock   # Unix socket for curl requests to Docker API
            - CURL_TIMEOUT=${CURL_TIMEOUT:-30}     # --max-time seconds for curl requests to Docker API
            - WEBHOOK_URL=${WEBHOOK_URL}    # post message to the webhook if a container was restarted (or restart failed)
        restart: always
        image: digilato/autoheal:${AUTOHEAL_VERSION:-latest}