version: '3.3'
services:
    watchtower:
        container_name: watchtower
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
            - TZ=America/Toronto
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
            - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
            - 'WATCHTOWER_SCHEDULE=0 0 0 * * *'
            - WATCHTOWER_MONITOR_ONLY=true
        restart: always
        image: containrrr/watchtower